const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'lib/constants/languages.ts');
let code = fs.readFileSync(filePath, 'utf8');

const additions = {
  en: {
    dashboardTitle: 'Krishi Bandhu Dashboard',
    registeredFarmerLabel: 'REGISTERED FARMER',
    loadingProfile: 'Loading Profile...',
    mobileLabel: 'Mobile',
    locationLabel: 'Location / District',
    registerNewCrop: 'Register New Crop Entry',
    recordedInfo: 'Recorded Farmer & Crop Information',
    recordsSaved: 'Records Saved in Postgres',
    syncing: 'Syncing records with Supabase Postgres...',
    noEntries: 'No crop entries recorded yet.',
    clickRegisterMsg: 'Click "Register New Crop Entry" to submit crop & loan details.',
    addEntryHeader: 'Add Farmer / Crop Entry',
    cancel: 'Cancel',
    submitEntry: 'Submit Entry',
    cropRecordNum: 'CROP RECORD',
    savedToSupabase: 'Saved to Supabase',
    soilTypeDisp: 'Soil Type',
    irrigationDisp: 'Irrigation',
    sowingDateDisp: 'Sowing Date',
    expectedHarvestDisp: 'Expected Harvest',
    loanDueDateDisp: 'Loan Due Date',
    approxLoanAmt: 'Approximate Loan Amount',
    consultAI: 'Consult Krishi AI',
    backToDashboard: 'Back to Dashboard',
    aiAssistant: 'Krishi AI Assistant',
    consultingFor: 'Consulting for Crop Record',
    askAIPlaceholder: 'Ask Krishi AI about fertilizers, weather, or crop health...',
    send: 'Send',
    govOfIndia: 'Government of India',
    aiGreeting: 'Namaste! I am Krishi AI, your virtual agricultural assistant. I see you are consulting about your recorded crop. How can I assist you with farming practices, pest control, or weather forecasts today?',
    aiSimulated: 'This is a simulated response. Once the AI backend is connected, I will provide tailored agricultural advice based on this crop\'s data!'
  },
  hi: {
    dashboardTitle: 'कृषि बंधु डैशबोर्ड',
    registeredFarmerLabel: 'पंजीकृत किसान',
    loadingProfile: 'प्रोफ़ाइल लोड हो रही है...',
    mobileLabel: 'मोबाइल',
    locationLabel: 'स्थान / जिला',
    registerNewCrop: 'नई फसल प्रविष्टि दर्ज करें',
    recordedInfo: 'दर्ज किसान और फसल की जानकारी',
    recordsSaved: 'सुपाबेस में दर्ज रिकॉर्ड',
    syncing: 'सुपाबेस पोस्टग्रेस के साथ रिकॉर्ड सिंक हो रहे हैं...',
    noEntries: 'अभी तक कोई फसल प्रविष्टि दर्ज नहीं की गई है।',
    clickRegisterMsg: 'फसल और ऋण विवरण जमा करने के लिए "नई फसल प्रविष्टि दर्ज करें" पर क्लिक करें।',
    addEntryHeader: 'किसान / फसल प्रविष्टि जोड़ें',
    cancel: 'रद्द करें',
    submitEntry: 'प्रविष्टि जमा करें',
    cropRecordNum: 'फसल रिकॉर्ड',
    savedToSupabase: 'सुपाबेस में सहेजा गया',
    soilTypeDisp: 'मिट्टी का प्रकार',
    irrigationDisp: 'सिंचाई',
    sowingDateDisp: 'बुआई की तारीख',
    expectedHarvestDisp: 'अपेक्षित कटाई',
    loanDueDateDisp: 'ऋण देय तिथि',
    approxLoanAmt: 'अनुमानित ऋण राशि',
    consultAI: 'कृषि एआई से परामर्श करें',
    backToDashboard: 'डैशबोर्ड पर वापस जाएं',
    aiAssistant: 'कृषि एआई सहायक',
    consultingFor: 'फसल रिकॉर्ड के लिए परामर्श',
    askAIPlaceholder: 'कृषि एआई से उर्वरक, मौसम, या फसल स्वास्थ्य के बारे में पूछें...',
    send: 'भेजें',
    govOfIndia: 'भारत सरकार',
    aiGreeting: 'नमस्ते! मैं कृषि एआई हूँ, आपका आभासी कृषि सहायक। मैं देख रहा हूँ कि आप अपनी दर्ज फसल के बारे में परामर्श कर रहे हैं। मैं आज खेती के तरीकों, कीट नियंत्रण, या मौसम के पूर्वानुमान के साथ आपकी कैसे मदद कर सकता हूँ?',
    aiSimulated: 'यह एक सिम्युलेटेड प्रतिक्रिया है। एआई बैकएंड के कनेक्ट होने के बाद, मैं इस फसल के डेटा के आधार पर अनुरूप कृषि सलाह प्रदान करूँगा!'
  },
  ta: {
    dashboardTitle: 'கிருஷி பந்து டேஷ்போர்டு',
    registeredFarmerLabel: 'பதிவு செய்யப்பட்ட விவசாயி',
    loadingProfile: 'சுயவிவரம் ஏற்றப்படுகிறது...',
    mobileLabel: 'மொபைல்',
    locationLabel: 'இடம் / மாவட்டம்',
    registerNewCrop: 'புதிய பயிர் பதிவைச் சேர்க்க',
    recordedInfo: 'பதிவு செய்யப்பட்ட விவசாயி & பயிர் தகவல்',
    recordsSaved: 'போஸ்ட்கிரெஸில் சேமிக்கப்பட்ட பதிவுகள்',
    syncing: 'சுபாபேஸ் போஸ்ட்கிரெஸ் உடன் பதிவுகள் ஒத்திசைக்கப்படுகின்றன...',
    noEntries: 'இதுவரை எந்த பயிர் பதிவுகளும் இல்லை.',
    clickRegisterMsg: 'பயிர் மற்றும் கடன் விவரங்களைச் சமர்ப்பிக்க "புதிய பயிர் பதிவைச் சேர்க்க" என்பதைக் கிளிக் செய்யவும்.',
    addEntryHeader: 'விவசாயி / பயிர் பதிவைச் சேர்',
    cancel: 'ரத்துசெய்',
    submitEntry: 'பதிவைச் சமர்ப்பி',
    cropRecordNum: 'பயிர் பதிவு',
    savedToSupabase: 'சுபாபேஸில் சேமிக்கப்பட்டது',
    soilTypeDisp: 'மண் வகை',
    irrigationDisp: 'பாசனம்',
    sowingDateDisp: 'விதைப்பு தேதி',
    expectedHarvestDisp: 'எதிர்பார்க்கப்படும் அறுவடை',
    loanDueDateDisp: 'கடன் திருப்பிச் செலுத்தும் தேதி',
    approxLoanAmt: 'தோராயமான கடன் தொகை',
    consultAI: 'கிருஷி AI ஐ அணுகவும்',
    backToDashboard: 'டேஷ்போர்டுக்குத் திரும்பு',
    aiAssistant: 'கிருஷி AI உதவியாளர்',
    consultingFor: 'பயிர் பதிவுக்கான ஆலோசனை',
    askAIPlaceholder: 'உரங்கள், வானிலை அல்லது பயிர் ஆரோக்கியம் குறித்து கிருஷி AI இடம் கேளுங்கள்...',
    send: 'அனுப்பு',
    govOfIndia: 'இந்திய அரசு',
    aiGreeting: 'வணக்கம்! நான் கிருஷி AI, உங்கள் மெய்நிகர் விவசாய உதவியாளர். இன்று உங்களுக்கு எப்படி உதவ முடியும்?',
    aiSimulated: 'இது ஒரு மாதிரி பதில். AI இணைக்கப்பட்டவுடன் விரிவான பதில்கள் கிடைக்கும்!'
  },
  te: {
    dashboardTitle: 'కృషి బంధు డాష్‌బోర్డ్',
    registeredFarmerLabel: 'నమోదైన రైతు',
    loadingProfile: 'ప్రొఫైల్ లోడ్ అవుతోంది...',
    mobileLabel: 'మొబైల్',
    locationLabel: 'ప్రాంతం / జిల్లా',
    registerNewCrop: 'కొత్త పంట నమోదు చేయండి',
    recordedInfo: 'నమోదైన రైతు & పంట సమాచారం',
    recordsSaved: 'పోస్ట్‌గ్రెస్‌లో సేవ్ చేయబడిన రికార్డులు',
    syncing: 'డేటాబేస్‌తో సమకాలీకరించబడుతోంది...',
    noEntries: 'ఇంకా ఎలాంటి పంట రికార్డులు లేవు.',
    clickRegisterMsg: 'పంట వివరాలను సమర్పించడానికి క్లిక్ చేయండి.',
    addEntryHeader: 'రైతు / పంట వివరాలు జోడించండి',
    cancel: 'రద్దు చేయి',
    submitEntry: 'సమర్పించు',
    cropRecordNum: 'పంట రికార్డ్',
    savedToSupabase: 'డేటాబేస్‌లో సేవ్ చేయబడింది',
    soilTypeDisp: 'నేల రకం',
    irrigationDisp: 'నీటి పారుదల',
    sowingDateDisp: 'విత్తిన తేదీ',
    expectedHarvestDisp: 'అంచనా కోత',
    loanDueDateDisp: 'గడువు తేదీ',
    approxLoanAmt: 'అంచనా రుణ మొత్తం',
    consultAI: 'కృషి AI ని అడగండి',
    backToDashboard: 'డాష్‌బోర్డ్‌కు తిరిగి వెళ్ళండి',
    aiAssistant: 'కృషి AI సహాయకుడు',
    consultingFor: 'పంట రికార్డ్ కోసం సంప్రదింపులు',
    askAIPlaceholder: 'ఎరువులు, వాతావరణం గురించి అడగండి...',
    send: 'పంపండి',
    govOfIndia: 'భారత ప్రభుత్వం',
    aiGreeting: 'నమస్కారం! నేను కృషి AI ని. నేను మీకు ఎలా సహాయపడగలను?',
    aiSimulated: 'ఇది నమూనా ప్రతిస్పందన మాత్రమే.'
  },
  mr: {
    dashboardTitle: 'कृषी बंधू डॅशबोर्ड',
    registeredFarmerLabel: 'नोंदणीकृत शेतकरी',
    loadingProfile: 'प्रोफाइल लोड होत आहे...',
    mobileLabel: 'मोबाईल',
    locationLabel: 'स्थान / जिल्हा',
    registerNewCrop: 'नवीन पीक नोंदणी करा',
    recordedInfo: 'नोंदणीकृत शेतकरी आणि पीक माहिती',
    recordsSaved: 'डेटाबेसमध्ये जतन केलेल्या नोंदी',
    syncing: 'डेटाबेससह सिंक करत आहे...',
    noEntries: 'अद्याप कोणतीही पीक नोंदणी नाही.',
    clickRegisterMsg: 'माहिती सबमिट करण्यासाठी क्लिक करा.',
    addEntryHeader: 'शेतकरी / पीक नोंदणी जोडा',
    cancel: 'रद्द करा',
    submitEntry: 'सबमिट करा',
    cropRecordNum: 'पीक रेकॉर्ड',
    savedToSupabase: 'सुपाबेसमध्ये जतन केले',
    soilTypeDisp: 'मातीचा प्रकार',
    irrigationDisp: 'सिंचन',
    sowingDateDisp: 'पेरणीची तारीख',
    expectedHarvestDisp: 'अपेक्षित कापणी',
    loanDueDateDisp: 'कर्ज परतफेडीची तारीख',
    approxLoanAmt: 'अंदाजित कर्ज रक्कम',
    consultAI: 'कृषी AI चा सल्ला घ्या',
    backToDashboard: 'डॅशबोर्डवर परत जा',
    aiAssistant: 'कृषी AI सहाय्यक',
    consultingFor: 'पीक रेकॉर्डसाठी सल्लामसलत',
    askAIPlaceholder: 'खते किंवा हवामानाबद्दल विचारा...',
    send: 'पाठवा',
    govOfIndia: 'भारत सरकार',
    aiGreeting: 'नमस्कार! मी कृषी AI आहे. मी तुम्हाला कशी मदत करू शकतो?',
    aiSimulated: 'हा केवळ नमुना प्रतिसाद आहे.'
  },
  bn: {
    dashboardTitle: 'কৃষি বন্ধু ড্যাশবোর্ড',
    registeredFarmerLabel: 'নিবন্ধিত কৃষক',
    loadingProfile: 'প্রোফাইল লোড হচ্ছে...',
    mobileLabel: 'মোবাইল',
    locationLabel: 'অবস্থান / জেলা',
    registerNewCrop: 'নতুন ফসল নিবন্ধন করুন',
    recordedInfo: 'নিবন্ধিত কৃষক ও ফসলের তথ্য',
    recordsSaved: 'ডাটাবেসে সংরক্ষিত রেকর্ড',
    syncing: 'ডাটাবেসের সাথে সিঙ্ক করা হচ্ছে...',
    noEntries: 'এখনও কোনো ফসলের রেকর্ড নেই।',
    clickRegisterMsg: 'তথ্য জমা দিতে ক্লিক করুন।',
    addEntryHeader: 'কৃষক / ফসলের তথ্য যোগ করুন',
    cancel: 'বাতিল করুন',
    submitEntry: 'জমা দিন',
    cropRecordNum: 'ফসলের রেকর্ড',
    savedToSupabase: 'সুপাবেসে সংরক্ষিত',
    soilTypeDisp: 'মাটির ধরন',
    irrigationDisp: 'সেচ',
    sowingDateDisp: 'বপনের তারিখ',
    expectedHarvestDisp: 'প্রত্যাশিত ফসল কাটা',
    loanDueDateDisp: 'ঋণ পরিশোধের তারিখ',
    approxLoanAmt: 'আনুমানিক ঋণের পরিমাণ',
    consultAI: 'কৃষি এআই-এর সাথে পরামর্শ করুন',
    backToDashboard: 'ড্যাশবোর্ডে ফিরে যান',
    aiAssistant: 'কৃষি এআই সহকারী',
    consultingFor: 'ফসলের রেকর্ডের জন্য পরামর্শ',
    askAIPlaceholder: 'সার বা আবহাওয়া সম্পর্কে জিজ্ঞাসা করুন...',
    send: 'পাঠান',
    govOfIndia: 'ভারত সরকার',
    aiGreeting: 'নমস্কার! আমি কৃষি এআই। আমি আপনাকে কীভাবে সাহায্য করতে পারি?',
    aiSimulated: 'এটি একটি সিমুলেটেড প্রতিক্রিয়া।'
  }
};

for (const [lang, keys] of Object.entries(additions)) {
  const regex = new RegExp(`(${lang}:\\s*{[\\s\\S]*?)(},\n)`, 'g');
  const innerString = Object.entries(keys).map(([k, v]) => `    ${k}: '${v.replace(/'/g, "\\'")}',`).join('\n');
  code = code.replace(regex, `$1${innerString}\n$2`);
}

fs.writeFileSync(filePath, code);
console.log('Language file updated!');
