export interface LanguageOption {
  code: string;
  name: string;
  nativeName: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिंदी' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' }
];

export const UI_TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    appTitle: 'Krishi Bandhu',
    portalSubtitle: 'Farmer & Crop Information Registration Portal',
    selectLanguage: 'Select Preferred Language',
    stepLanguage: '1. Language',
    stepAccount: '2. Account Details',
    stepLocation: '3. Location & District',
    stepCropLand: '4. Crop & Land Size',
    stepAgriDetails: '5. Soil & Irrigation',
    stepFinancial: '6. Loan Details',
    fullName: 'Full Name',
    mobileNumber: 'Mobile Number',
    password: 'Password',
    loginTitle: 'Sign In to Krishi Bandhu',
    signupTitle: 'Farmer Registration',
    locationTitle: 'Location / District Information',
    stateLabel: 'State',
    districtLabel: 'District',
    manualInputToggle: 'Or enter location manually',
    manualAddressLabel: 'Manual Location / Address',
    fetchGpsLocation: '📍 Auto-detect GPS Location',
    cropLabel: 'Select Crop',
    customCropLabel: 'Specify Crop Name',
    landSizeLabel: 'Land Size',
    landUnitLabel: 'Land Unit',
    sowingDateLabel: 'Sowing Date',
    irrigationTypeLabel: 'Irrigation Type',
    soilTypeLabel: 'Soil Type',
    expectedHarvestDateLabel: 'Expected Harvest Date',
    loanAmountLabel: 'Approximate Loan Amount (₹)',
    loanDueDateLabel: 'Loan Due Date',
    nextButton: 'Next Step',
    backButton: 'Back',
    submitButton: 'Submit Farmer Data to Supabase',
    signInButton: 'Sign In',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already registered?',
    saving: 'Saving data to Supabase Postgres...',
    successMsg: 'Farmer & Crop Details successfully registered!',
  },
  hi: {
    appTitle: 'कृषि बंधु',
    portalSubtitle: 'किसान और फसल सूचना पंजीकरण पोर्टल',
    selectLanguage: 'अपनी भाषा चुनें',
    stepLanguage: '1. भाषा',
    stepAccount: '2. खाता विवरण',
    stepLocation: '3. स्थान और जिला',
    stepCropLand: '4. फसल और भूमि का आकार',
    stepAgriDetails: '5. मिट्टी और सिंचाई',
    stepFinancial: '6. ऋण विवरण',
    fullName: 'पूरा नाम',
    mobileNumber: 'मोबाइल नंबर',
    password: 'पासवर्ड',
    loginTitle: 'कृषि बंधु में साइन इन करें',
    signupTitle: 'किसान पंजीकरण',
    locationTitle: 'स्थान / जिला जानकारी',
    stateLabel: 'राज्य',
    districtLabel: 'जिला',
    manualInputToggle: 'या स्थान स्वयं लिखें',
    manualAddressLabel: 'स्थान / पता दर्ज करें',
    fetchGpsLocation: '📍 जीपीएस से स्थान प्राप्त करें',
    cropLabel: 'फसल चुनें',
    customCropLabel: 'फसल का नाम लिखें',
    landSizeLabel: 'भूमि का आकार',
    landUnitLabel: 'इकाई',
    sowingDateLabel: 'बुआई की तारीख',
    irrigationTypeLabel: 'सिंचाई का प्रकार',
    soilTypeLabel: 'मिट्टी का प्रकार',
    expectedHarvestDateLabel: 'कटाई की संभावित तारीख',
    loanAmountLabel: 'अनुमानित ऋण राशि (₹)',
    loanDueDateLabel: 'ऋण भुगतान की तारीख',
    nextButton: 'आगे बढ़ें',
    backButton: 'पीछे जाएं',
    submitButton: 'सुपाबेस डेटाबेस में जमा करें',
    signInButton: 'साइन इन करें',
    dontHaveAccount: 'खाता नहीं है?',
    alreadyHaveAccount: 'पहले से पंजीकृत हैं?',
    saving: 'सुपाबेस में डेटा सहेजा जा रहा है...',
    successMsg: 'किसान और फसल की जानकारी सफलतापूर्वक दर्ज की गई!',
  },
  ta: {
    appTitle: 'கிருஷி பந்து',
    portalSubtitle: 'விவசாயி & பயிர் தகவல் பதிவு மையம்',
    selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    stepLanguage: '1. மொழி',
    stepAccount: '2. கணக்கு விவரங்கள்',
    stepLocation: '3. இடம் & மாவட்டம்',
    stepCropLand: '4. பயிர் & நில அளவு',
    stepAgriDetails: '5. மண் & பாசனம்',
    stepFinancial: '6. கடன் விவரங்கள்',
    fullName: 'முழு பெயர்',
    mobileNumber: 'மொபைல் எண்',
    password: 'கடவுச்சொல்',
    loginTitle: 'உள்நுழைக',
    signupTitle: 'விவசாயி பதிவு',
    locationTitle: 'இடம் / மாவட்டம்',
    stateLabel: 'மாநிலம்',
    districtLabel: 'மாவட்டம்',
    manualInputToggle: 'அல்லது நேரடியாக எழுதவும்',
    manualAddressLabel: 'முகவரி',
    fetchGpsLocation: '📍 ஜிபிஎஸ் மூலம் கண்டறி',
    cropLabel: 'பயிர் தேர்வு',
    customCropLabel: 'பயிர் பெயர்',
    landSizeLabel: 'நில அளவு',
    landUnitLabel: 'அலகு',
    sowingDateLabel: 'விதைப்பு தேதி',
    irrigationTypeLabel: 'பாசன முறை',
    soilTypeLabel: 'மண் வகை',
    expectedHarvestDateLabel: 'அறுவடை தேதி',
    loanAmountLabel: 'கடன் தொகை (₹)',
    loanDueDateLabel: 'கடன் திருப்பி செலுத்தும் தேதி',
    nextButton: 'அடுத்து',
    backButton: 'பின்னால்',
    submitButton: 'சமர்ப்பி',
    signInButton: 'உள்நுழைக',
    dontHaveAccount: 'கணக்கு இல்லையா?',
    alreadyHaveAccount: 'ஏற்கனவே பதிந்துவிட்டீர்களா?',
    saving: 'சேமிக்கப்படுகிறது...',
    successMsg: 'வெற்றிகரமாக பதிவு செய்யப்பட்டது!',
  },
  te: {
    appTitle: 'కృషి బంధు',
    portalSubtitle: 'రైతు మరియు పంట సమాచార నమోదు పోర్టల్',
    selectLanguage: 'మీ ప్రాధాన్య భాషను ఎంచుకోండి',
    stepLanguage: '1. భాష',
    stepAccount: '2. ఖాతా వివరాలు',
    stepLocation: '3. ప్రాంతం & జిల్లా',
    stepCropLand: '4. పంట & భూమి పరిమాణం',
    stepAgriDetails: '5. నేల & నీటి పారుదల',
    stepFinancial: '6. రుణం వివరాలు',
    fullName: 'పూర్తి పేరు',
    mobileNumber: 'మొబైల్ సంఖ్య',
    password: 'పాస్‌వర్డ్',
    loginTitle: 'కృషి బంధులోకి లాగిన్ అవ్వండి',
    signupTitle: 'రైతు నమోదు',
    locationTitle: 'ప్రాంతం / జిల్లా సమాచారం',
    stateLabel: 'రాష్ట్రం',
    districtLabel: 'జిల్లా',
    manualInputToggle: 'లేదా చిరునామాను మాన్యువల్‌గా నమోదు చేయండి',
    manualAddressLabel: 'మాన్యువల్ ప్రాంతం / చిరునామా',
    fetchGpsLocation: '📍 జీపీఎస్ ద్వారా లొకేషన్‌ను కనుగొనండి',
    cropLabel: 'పంటను ఎంచుకోండి',
    customCropLabel: 'పంట పేరును పేర్కొనండి',
    landSizeLabel: 'భూమి పరిమాణం',
    landUnitLabel: 'యూనిట్',
    sowingDateLabel: 'విత్తనాలు నాటిన తేదీ',
    irrigationTypeLabel: 'నీటి పారుదల రకం',
    soilTypeLabel: 'నేల రకం',
    expectedHarvestDateLabel: 'కోత అంచనా తేదీ',
    loanAmountLabel: 'అంచనా రుణ మొత్తం (₹)',
    loanDueDateLabel: 'రుణం చెల్లింపు గడువు తేదీ',
    nextButton: 'తరువాతి మెట్టు',
    backButton: 'వెనుకకు',
    submitButton: 'సుపాబేస్ డేటాబేస్‌లో సమర్పించండి',
    signInButton: 'సైన్ ఇన్ చేయండి',
    dontHaveAccount: 'ఖాతా లేదా?',
    alreadyHaveAccount: 'ఇప్పటికే నమోదయ్యారా?',
    saving: 'డేటాను భద్రపరుస్తోంది...',
    successMsg: 'రైతు మరియు పంట సమాచారం విజయవంతంగా నమోదైంది!',
  },
  mr: {
    appTitle: 'कृषी बंधू',
    portalSubtitle: 'शेतकरी व पीक माहिती नोंदणी पोर्टल',
    selectLanguage: 'आपली आवडती भाषा निवडा',
    stepLanguage: '1. भाषा',
    stepAccount: '2. खाते तपशील',
    stepLocation: '3. स्थान व जिल्हा',
    stepCropLand: '4. पीक व जमिनीचे क्षेत्र',
    stepAgriDetails: '5. माती व सिंचन',
    stepFinancial: '6. कर्जाचा तपशील',
    fullName: 'पूर्ण नाव',
    mobileNumber: 'मोबाईल नंबर',
    password: 'पासवर्ड',
    loginTitle: 'कृषी बंधू मध्ये साइन इन करा',
    signupTitle: 'शेतकरी नोंदणी',
    locationTitle: 'स्थान / जिल्हा माहिती',
    stateLabel: 'राज्य',
    districtLabel: 'जिल्हा',
    manualInputToggle: 'किंवा स्थान स्वतः टाईप करा',
    manualAddressLabel: 'स्थान / पत्ता',
    fetchGpsLocation: '📍 जीपीएस द्वारे स्थान मिळवा',
    cropLabel: 'पीक निवडा',
    customCropLabel: 'पिकाचे नाव लिहा',
    landSizeLabel: 'जमिनीचे क्षेत्रफळ',
    landUnitLabel: 'एकक',
    sowingDateLabel: 'पेरणीची तारीख',
    irrigationTypeLabel: 'सिंचनाचा प्रकार',
    soilTypeLabel: 'मातीचा प्रकार',
    expectedHarvestDateLabel: 'कापणीची अपेक्षित तारीख',
    loanAmountLabel: 'अंदाजित कर्ज रक्कम (₹)',
    loanDueDateLabel: 'कर्ज परतफेडीची तारीख',
    nextButton: 'पुढील पायरी',
    backButton: 'मागे',
    submitButton: 'सुपाबेस डेटाबेसमध्ये सबमिट करा',
    signInButton: 'साइन इन करा',
    dontHaveAccount: 'खाते नाही का?',
    alreadyHaveAccount: 'आधीच नोंदणी केली आहे?',
    saving: 'डेटा जतन करत आहे...',
    successMsg: 'शेतकरी आणि पीक माहिती यशस्वीरित्या नोंदवली गेली!',
  },
  bn: {
    appTitle: 'কৃষি বন্ধু',
    portalSubtitle: 'কৃষক ও ফসলের তথ্য নিবন্ধন পোর্টাল',
    selectLanguage: 'আপনার পছন্দের ভাষা নির্বাচন করুন',
    stepLanguage: '১. ভাষা',
    stepAccount: '২. অ্যাকাউন্টের বিবরণ',
    stepLocation: '৩. অবস্থান ও জেলা',
    stepCropLand: '৪. ফসল ও জমির পরিমাণ',
    stepAgriDetails: '৫. মাটি ও সেচ ব্যবস্থা',
    stepFinancial: '৬. ঋণের বিবরণ',
    fullName: 'সম্পূর্ণ নাম',
    mobileNumber: 'মোবাইল নম্বর',
    password: 'পাসওয়ার্ড',
    loginTitle: 'কৃষি বন্ধুতে সাইন ইন করুন',
    signupTitle: 'কৃষক নিবন্ধন',
    locationTitle: 'অবস্থান / জেলার তথ্য',
    stateLabel: 'রাজ্য',
    districtLabel: 'জেলা',
    manualInputToggle: 'অথবা ঠিকানা নিজে লিখুন',
    manualAddressLabel: 'হাতে লেখা ঠিকানা / অবস্থান',
    fetchGpsLocation: '📍 জিপিএস দিয়ে অবস্থান সনাক্ত করুন',
    cropLabel: 'ফসল নির্বাচন করুন',
    customCropLabel: 'ফসলের নাম লিখুন',
    landSizeLabel: 'জমির পরিমাণ',
    landUnitLabel: 'একক',
    sowingDateLabel: 'বপনের তারিখ',
    irrigationTypeLabel: 'সেচের ধরন',
    soilTypeLabel: 'মাটির ধরন',
    expectedHarvestDateLabel: 'ফসল কাটার আনুমানিক তারিখ',
    loanAmountLabel: 'আনুমানিক ঋণের পরিমাণ (₹)',
    loanDueDateLabel: 'ঋণ পরিশোধের তারিখ',
    nextButton: 'পরবর্তী ধাপ',
    backButton: 'পেছনে যান',
    submitButton: 'সুপাবেস ডাটাবেসে জমা দিন',
    signInButton: 'সাইন ইন করুন',
    dontHaveAccount: 'অ্যাকাউন্ট নেই?',
    alreadyHaveAccount: 'ইতিমধ্যে নিবন্ধিত?',
    saving: 'তথ্য সংরক্ষণ করা হচ্ছে...',
    successMsg: 'কৃষক এবং ফসলের তথ্য সফলভাবে নিবন্ধিত হয়েছে!',
  }
};

export function getTranslation(langCode: string, key: string): string {
  const dict = UI_TRANSLATIONS[langCode] || UI_TRANSLATIONS['en'];
  return dict[key] || UI_TRANSLATIONS['en'][key] || key;
}
