export interface LanguageOption {
  code: string;
  name: string;
  nativeName: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिंदी' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' }
];

export const UI_TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    appTitle: 'Krishi Bandhu',
    portalSubtitle: 'Farmer & Crop Information Registration Portal',
    selectLanguage: 'Select Preferred Language',
    stepLanguage: '1. Language',
    stepAccount: '2. Account Details',
    stepLocation: '3. Location & District',
    stepCropLand: '4. Crop & Land Size',
    stepAgriDetails: '5. Soil & Irrigation',
    stepFinancial: '6. Loan Details',
    fullName: 'Full Name',
    mobileNumber: 'Mobile Number',
    password: 'Password',
    loginTitle: 'Sign In to Krishi Bandhu',
    signupTitle: 'Farmer Registration',
    locationTitle: 'Location / District Information',
    stateLabel: 'State',
    districtLabel: 'District',
    manualInputToggle: 'Or enter location manually',
    manualAddressLabel: 'Manual Location / Address',
    fetchGpsLocation: 'Auto-detect GPS Location',
    cropLabel: 'Select Crop',
    customCropLabel: 'Specify Crop Name',
    landSizeLabel: 'Land Size',
    landUnitLabel: 'Land Unit',
    sowingDateLabel: 'Sowing Date',
    irrigationTypeLabel: 'Irrigation Type',
    soilTypeLabel: 'Soil Type',
    expectedHarvestDateLabel: 'Expected Harvest Date',
    loanAmountLabel: 'Approximate Loan Amount (₹)',
    loanDueDateLabel: 'Loan Due Date',
    nextButton: 'Next Step',
    backButton: 'Back',
    submitButton: 'Submit Farmer Data to Supabase',
    signInButton: 'Sign In',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already registered?',
    saving: 'Saving data to Supabase Postgres...',
    successMsg: 'Farmer & Crop Details successfully registered!',
      dashboardTitle: 'Krishi Bandhu Dashboard',
    registeredFarmerLabel: 'REGISTERED FARMER',
    loadingProfile: 'Loading Profile...',
    mobileLabel: 'Mobile',
    locationLabel: 'Location / District',
    registerNewCrop: 'Register New Crop Entry',
    recordedInfo: 'Recorded Farmer & Crop Information',
    recordsSaved: 'Records Saved in Postgres',
    syncing: 'Syncing records with Supabase Postgres...',
    noEntries: 'No crop entries recorded yet.',
    clickRegisterMsg: 'Click "Register New Crop Entry" to submit crop & loan details.',
    addEntryHeader: 'New Registration',
    cancel: 'Cancel',
    submitEntry: 'Submit Entry',
    cropRecordNum: 'CROP RECORD',
    savedToSupabase: 'Saved',
    soilTypeDisp: 'Soil Type',
    irrigationDisp: 'Irrigation',
    sowingDateDisp: 'Sowing Date',
    expectedHarvestDisp: 'Expected Harvest',
    loanDueDateDisp: 'Loan Due Date',
    approxLoanAmt: 'Approximate Loan Amount',
    consultAI: 'Consult Krishi AI',
    backToDashboard: 'Back to Dashboard',
    aiAssistant: 'Krishi AI Assistant',
    consultingFor: 'Consulting for Crop Record',
    askAIPlaceholder: 'Ask Krishi AI about fertilizers, weather, or crop health...',
    send: 'Send',
    govOfIndia: 'Government of India',
    aiGreeting: 'Namaste! I am Krishi AI, your virtual agricultural assistant. I see you are consulting about your recorded crop. How can I assist you with farming practices, pest control, or weather forecasts today?',
    aiSimulated: 'This is a simulated response. Once the AI backend is connected, I will provide tailored agricultural advice based on this crop\'s data!',
    advIntro: 'Hello! I am your Krishi Bandhu Advisory Assistant. To give you the best advice, I need to ask you 5 quick questions about your farm.',
    advAskCrop: 'First, which crop are you growing?',
    advAskStage: 'What is the current growth stage of your crop?',
    advAskSoil: 'What type of soil do you have?',
    advAskPesticide: 'Have you applied pesticide recently?',
    advAskRainfall: 'What was the average rainfall (in mm) over the last 7 days?',
    advFetching: 'Thank you! Analyzing your data and fetching the advisory report...',
    advDone: 'Advisory session complete.',
    advSelectOption: 'Please select an option above.',
    advError: 'Could not connect to the Advisory Backend. Make sure the FastAPI server is running!',
    advYes: 'Yes, applied',
    advNo: 'No',
    marketPageTitle: 'Live Mandi Prices',
    marketPageDesc: 'Compare live agricultural market prices across your state to find the most profitable Mandi for your crop.',
    marketSelectCrop: 'Select Crop to Check Prices',
    marketChecking: 'Fetching Live Mandi Prices...',
    marketCheckBtn: 'Check Mandi Prices',
    marketNoProfile: 'No Profile Found',
    marketReturnDash: 'Please return to the Dashboard to add your crop and profile details first.',
    marketBestPrice: 'Highest Paying Mandis in',
    marketMandiName: 'Mandi Name',
    marketArrivalDate: 'Date',
    marketModalPrice: 'Price (₹/Quintal)',
    marketMinMax: 'Min - Max (₹)',
    alertDispatchedBanner: 'Critical Risk Detected. An emergency alert with your profile and location has been dispatched to the local agricultural officer.',
    outstandingLoanAmt: 'Outstanding Balance (₹)',
    annualIncome: 'Estimated Annual Income (₹)',
    distressEngineTitle: 'Farmer Distress Engine',
    distressEngineDesc: 'This tool analyzes real-time weather, market prices, and financial history to predict agricultural distress risk.',
    distressResultTitle: 'Distress Assessment Result',
    distressRisk: 'RISK',
    distressKeyFactors: 'Key Risk Factors Identified',
    distressNoRisk: 'No immediate risk factors detected.',
    distressCalcAnother: 'Calculate Another Crop',
    distressSelectCrop: 'Select Crop to Analyze',
    distressDataSummary: 'Data Summary (Auto-Filled)',
    distressLocation: 'Location',
    distressLoanAmt: 'Loan Amount',
    distressAnalyzing: 'Analyzing Live Data...',
    distressCalcBtn: 'Calculate Distress Score',
    distressNoProfile: 'No Profile Found',
    distressReturnDash: 'Please return to the Dashboard to add your crop and profile details first.',
    riskLow: 'LOW',
    riskMedium: 'MEDIUM',
    riskHigh: 'HIGH',
    advSoilSfx: 'Soil',
    crop_rice: 'Rice',
    crop_wheat: 'Wheat',
    crop_maize: 'Maize',
    crop_chickpea: 'Chickpea',
    crop_pigeon_pea: 'Pigeon Pea',
    crop_cotton: 'Cotton',
    crop_sugarcane: 'Sugarcane',
    crop_tomato: 'Tomato',
    crop_potato: 'Potato',
    stage_sowing: 'Sowing',
    stage_vegetative: 'Vegetative',
    stage_flowering: 'Flowering',
    stage_fruiting: 'Fruiting',
    stage_maturity: 'Maturity',
    soil_sandy: 'Sandy',
    soil_loamy: 'Loamy',
    soil_clay: 'Clay',
    logOutBtn: 'Log Out',
    distressScoreTitle: 'Financial Distress Score',
    distressScoreDesc: 'Calculate risk assessment based on regional weather & market data',
    calculateScoreBtn: 'Calculate Score',
    liveMandiTitle: 'Live Mandi Prices',
    mandiDesc: 'Compare agricultural market prices across your state to find the most profitable Mandi.',
    checkPricesBtn: 'Check Prices',
    syncingCropStatus: '⏳ Syncing...',
},
  hi: {
    appTitle: 'कृषि बंधु',
    portalSubtitle: 'किसान और फसल सूचना पंजीकरण पोर्टल',
    selectLanguage: 'अपनी भाषा चुनें',
    stepLanguage: '1. भाषा',
    stepAccount: '2. खाता विवरण',
    stepLocation: '3. स्थान और जिला',
    stepCropLand: '4. फसल और भूमि का आकार',
    stepAgriDetails: '5. मिट्टी और सिंचाई',
    stepFinancial: '6. ऋण विवरण',
    fullName: 'पूरा नाम',
    mobileNumber: 'मोबाइल नंबर',
    password: 'पासवर्ड',
    loginTitle: 'कृषि बंधु में साइन इन करें',
    signupTitle: 'किसान पंजीकरण',
    locationTitle: 'स्थान / जिला जानकारी',
    stateLabel: 'राज्य',
    districtLabel: 'जिला',
    manualInputToggle: 'या स्थान स्वयं लिखें',
    manualAddressLabel: 'स्थान / पता दर्ज करें',
    fetchGpsLocation: 'जीपीएस से स्थान प्राप्त करें',
    cropLabel: 'फसल चुनें',
    customCropLabel: 'फसल का नाम लिखें',
    landSizeLabel: 'भूमि का आकार',
    landUnitLabel: 'इकाई',
    sowingDateLabel: 'बुआई की तारीख',
    irrigationTypeLabel: 'सिंचाई का प्रकार',
    soilTypeLabel: 'मिट्टी का प्रकार',
    expectedHarvestDateLabel: 'कटाई की संभावित तारीख',
    loanAmountLabel: 'अनुमानित ऋण राशि (₹)',
    loanDueDateLabel: 'ऋण भुगतान की तारीख',
    nextButton: 'आगे बढ़ें',
    backButton: 'पीछे जाएं',
    submitButton: 'सुपाबेस डेटाबेस में जमा करें',
    signInButton: 'साइन इन करें',
    dontHaveAccount: 'खाता नहीं है?',
    alreadyHaveAccount: 'पहले से पंजीकृत हैं?',
    saving: 'सुपाबेस में डेटा सहेजा जा रहा है...',
    successMsg: 'किसान और फसल की जानकारी सफलतापूर्वक दर्ज की गई!',
      dashboardTitle: 'कृषि बंधु डैशबोर्ड',
    registeredFarmerLabel: 'पंजीकृत किसान',
    loadingProfile: 'प्रोफ़ाइल लोड हो रही है...',
    mobileLabel: 'मोबाइल',
    locationLabel: 'स्थान / जिला',
    registerNewCrop: 'नई फसल प्रविष्टि दर्ज करें',
    recordedInfo: 'दर्ज किसान और फसल की जानकारी',
    recordsSaved: 'सुपाबेस में दर्ज रिकॉर्ड',
    syncing: 'सुपाबेस पोस्टग्रेस के साथ रिकॉर्ड सिंक हो रहे हैं...',
    noEntries: 'अभी तक कोई फसल प्रविष्टि दर्ज नहीं की गई है।',
    clickRegisterMsg: 'फसल और ऋण विवरण जमा करने के लिए "नई फसल प्रविष्टि दर्ज करें" पर क्लिक करें।',
    addEntryHeader: 'नया पंजीकरण',
    cancel: 'रद्द करें',
    submitEntry: 'प्रविष्टि जमा करें',
    cropRecordNum: 'फसल रिकॉर्ड',
    savedToSupabase: 'सहेजा गया',
    soilTypeDisp: 'मिट्टी का प्रकार',
    irrigationDisp: 'सिंचाई',
    sowingDateDisp: 'बुआई की तारीख',
    expectedHarvestDisp: 'अपेक्षित कटाई',
    loanDueDateDisp: 'ऋण देय तिथि',
    approxLoanAmt: 'अनुमानित ऋण राशि',
    consultAI: 'कृषि एआई से परामर्श करें',
    backToDashboard: 'डैशबोर्ड पर वापस जाएं',
    aiAssistant: 'कृषि एआई सहायक',
    consultingFor: 'फसल रिकॉर्ड के लिए परामर्श',
    askAIPlaceholder: 'कृषि एआई से उर्वरक, मौसम, या फसल स्वास्थ्य के बारे में पूछें...',
    send: 'भेजें',
    govOfIndia: 'भारत सरकार',
    aiGreeting: 'नमस्ते! मैं कृषि एआई हूँ, आपका आभासी कृषि सहायक। मैं देख रहा हूँ कि आप अपनी दर्ज फसल के बारे में परामर्श कर रहे हैं। मैं आज खेती के तरीकों, कीट नियंत्रण, या मौसम के पूर्वानुमान के साथ आपकी कैसे मदद कर सकता हूँ?',
    aiSimulated: 'यह एक सिम्युलेटेड प्रतिक्रिया है। एआई बैकएंड के कनेक्ट होने के बाद, मैं इस फसल के डेटा के आधार पर अनुरूप कृषि सलाह प्रदान करूँगा!',
    advIntro: 'नमस्ते! मैं आपका कृषि बंधु सलाहकार हूँ। आपको बेहतरीन सलाह देने के लिए, मुझे आपके खेत के बारे में 5 त्वरित प्रश्न पूछने हैं।',
    advAskCrop: 'सबसे पहले, आप कौन सी फसल उगा रहे हैं?',
    advAskStage: 'आपकी फसल के विकास का वर्तमान चरण क्या है?',
    advAskSoil: 'आपके पास किस प्रकार की मिट्टी है?',
    advAskPesticide: 'क्या आपने हाल ही में कीटनाशक का प्रयोग किया है?',
    advAskRainfall: 'पिछले 7 दिनों में औसत वर्षा (मिमी में) कितनी हुई?',
    advFetching: 'धन्यवाद! आपके डेटा का विश्लेषण कर रहा हूँ और रिपोर्ट ला रहा हूँ...',
    advDone: 'परामर्श सत्र पूरा हुआ।',
    advSelectOption: 'कृपया ऊपर से एक विकल्प चुनें।',
    advError: 'बैकएंड से कनेक्ट नहीं हो सका!',
    advYes: 'हाँ, किया है',
    advNo: 'नहीं',
    marketPageTitle: 'लाइव मंडी भाव',
    marketPageDesc: 'अपनी फसल के लिए सबसे लाभदायक मंडी खोजने के लिए अपने राज्य भर में लाइव कृषि बाजार भाव की तुलना करें।',
    marketSelectCrop: 'भाव जांचने के लिए फसल चुनें',
    marketChecking: 'लाइव मंडी भाव प्राप्त किए जा रहे हैं...',
    marketCheckBtn: 'मंडी भाव जांचें',
    marketNoProfile: 'कोई प्रोफ़ाइल नहीं मिली',
    marketReturnDash: 'कृपया अपनी फसल और प्रोफ़ाइल विवरण जोड़ने के लिए डैशबोर्ड पर लौटें।',
    marketBestPrice: 'में सबसे अधिक भुगतान करने वाली मंडियां',
    marketMandiName: 'मंडी का नाम',
    marketArrivalDate: 'दिनांक',
    marketModalPrice: 'भाव (₹/क्विंटल)',
    marketMinMax: 'न्यूनतम - अधिकतम (₹)',
    alertDispatchedBanner: 'गंभीर जोखिम का पता चला है। आपकी प्रोफ़ाइल और स्थान के साथ एक आपातकालीन अलर्ट स्थानीय कृषि अधिकारी को भेज दिया गया है।',
    outstandingLoanAmt: 'बकाया राशि (₹)',
    annualIncome: 'अनुमानित वार्षिक आय (₹)',
    distressEngineTitle: 'किसान संकट इंजन',
    distressEngineDesc: 'यह उपकरण कृषि संकट जोखिम की भविष्यवाणी करने के लिए मौसम, बाजार की कीमतों और वित्तीय इतिहास का विश्लेषण करता है।',
    distressResultTitle: 'संकट मूल्यांकन परिणाम',
    distressRisk: 'जोखिम',
    distressKeyFactors: 'प्रमुख जोखिम कारक',
    distressNoRisk: 'कोई तत्काल जोखिम कारक नहीं पाया गया।',
    distressCalcAnother: 'दूसरी फसल की गणना करें',
    distressSelectCrop: 'विश्लेषण के लिए फसल चुनें',
    distressDataSummary: 'डेटा सारांश (स्वतः भरा हुआ)',
    distressLocation: 'स्थान',
    distressLoanAmt: 'ऋण राशि',
    distressAnalyzing: 'लाइव डेटा का विश्लेषण किया जा रहा है...',
    distressCalcBtn: 'संकट स्कोर की गणना करें',
    distressNoProfile: 'कोई प्रोफ़ाइल नहीं मिली',
    distressReturnDash: 'कृपया अपनी फसल और प्रोफ़ाइल विवरण जोड़ने के लिए डैशबोर्ड पर लौटें।',
    riskLow: 'कम',
    riskMedium: 'मध्यम',
    riskHigh: 'उच्च',
    advSoilSfx: 'मिट्टी',
    crop_rice: 'चावल',
    crop_wheat: 'गेहूँ',
    crop_maize: 'मक्का',
    crop_chickpea: 'चना',
    crop_pigeon_pea: 'अरहर',
    crop_cotton: 'कपास',
    crop_sugarcane: 'गन्ना',
    crop_tomato: 'टमाटर',
    crop_potato: 'आलू',
    stage_sowing: 'बुवाई',
    stage_vegetative: 'वानस्पतिक',
    stage_flowering: 'फूल आना',
    stage_fruiting: 'फल आना',
    stage_maturity: 'परिपक्वता',
    soil_sandy: 'बलुई',
    soil_loamy: 'दोमट',
    soil_clay: 'चिकनी',
    logOutBtn: 'लॉग आउट',
    distressScoreTitle: 'वित्तीय संकट स्कोर',
    distressScoreDesc: 'क्षेत्रीय मौसम और बाजार डेटा के आधार पर जोखिम मूल्यांकन की गणना करें',
    calculateScoreBtn: 'स्कोर की गणना करें',
    liveMandiTitle: 'लाइव मंडी कीमतें',
    mandiDesc: 'सबसे लाभदायक मंडी खोजने के लिए अपने राज्य भर में कृषि बाजार की कीमतों की तुलना करें।',
    checkPricesBtn: 'कीमतें जांचें',
    syncingCropStatus: '⏳ सिंक हो रहा है...',
},
  ta: {
    appTitle: 'கிருஷி பந்து',
    portalSubtitle: 'விவசாயி & பயிர் தகவல் பதிவு மையம்',
    selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    stepLanguage: '1. மொழி',
    stepAccount: '2. கணக்கு விவரங்கள்',
    stepLocation: '3. இடம் & மாவட்டம்',
    stepCropLand: '4. பயிர் & நில அளவு',
    stepAgriDetails: '5. மண் & பாசனம்',
    stepFinancial: '6. கடன் விவரங்கள்',
    fullName: 'முழு பெயர்',
    mobileNumber: 'மொபைல் எண்',
    password: 'கடவுச்சொல்',
    loginTitle: 'உள்நுழைக',
    signupTitle: 'விவசாயி பதிவு',
    locationTitle: 'இடம் / மாவட்டம்',
    stateLabel: 'மாநிலம்',
    districtLabel: 'மாவட்டம்',
    manualInputToggle: 'அல்லது நேரடியாக எழுதவும்',
    manualAddressLabel: 'முகவரி',
    fetchGpsLocation: 'ஜிபிஎஸ் மூலம் கண்டறி',
    cropLabel: 'பயிர் தேர்வு',
    customCropLabel: 'பயிர் பெயர்',
    landSizeLabel: 'நில அளவு',
    landUnitLabel: 'அலகு',
    sowingDateLabel: 'விதைப்பு தேதி',
    irrigationTypeLabel: 'பாசன முறை',
    soilTypeLabel: 'மண் வகை',
    expectedHarvestDateLabel: 'அறுவடை தேதி',
    loanAmountLabel: 'கடன் தொகை (₹)',
    loanDueDateLabel: 'கடன் திருப்பி செலுத்தும் தேதி',
    nextButton: 'அடுத்து',
    backButton: 'பின்னால்',
    submitButton: 'சமர்ப்பி',
    signInButton: 'உள்நுழைக',
    dontHaveAccount: 'கணக்கு இல்லையா?',
    alreadyHaveAccount: 'ஏற்கனவே பதிந்துவிட்டீர்களா?',
    saving: 'சேமிக்கப்படுகிறது...',
    successMsg: 'வெற்றிகரமாக பதிவு செய்யப்பட்டது!',
      dashboardTitle: 'கிருஷி பந்து டேஷ்போர்டு',
    registeredFarmerLabel: 'பதிவு செய்யப்பட்ட விவசாயி',
    loadingProfile: 'சுயவிவரம் ஏற்றப்படுகிறது...',
    mobileLabel: 'மொபைல்',
    locationLabel: 'இடம் / மாவட்டம்',
    registerNewCrop: 'புதிய பயிர் பதிவைச் சேர்க்க',
    recordedInfo: 'பதிவு செய்யப்பட்ட விவசாயி & பயிர் தகவல்',
    recordsSaved: 'போஸ்ட்கிரெஸில் சேமிக்கப்பட்ட பதிவுகள்',
    syncing: 'சுபாபேஸ் போஸ்ட்கிரெஸ் உடன் பதிவுகள் ஒத்திசைக்கப்படுகின்றன...',
    noEntries: 'இதுவரை எந்த பயிர் பதிவுகளும் இல்லை.',
    clickRegisterMsg: 'பயிர் மற்றும் கடன் விவரங்களைச் சமர்ப்பிக்க "புதிய பயிர் பதிவைச் சேர்க்க" என்பதைக் கிளிக் செய்யவும்.',
    addEntryHeader: 'புதிய பதிவு',
    cancel: 'ரத்துசெய்',
    submitEntry: 'பதிவைச் சமர்ப்பி',
    cropRecordNum: 'பயிர் பதிவு',
    savedToSupabase: 'சேமிக்கப்பட்டது',
    soilTypeDisp: 'மண் வகை',
    irrigationDisp: 'பாசனம்',
    sowingDateDisp: 'விதைப்பு தேதி',
    expectedHarvestDisp: 'எதிர்பார்க்கப்படும் அறுவடை',
    loanDueDateDisp: 'கடன் திருப்பிச் செலுத்தும் தேதி',
    approxLoanAmt: 'தோராயமான கடன் தொகை',
    consultAI: 'கிருஷி AI ஐ அணுகவும்',
    backToDashboard: 'டேஷ்போர்டுக்குத் திரும்பு',
    aiAssistant: 'கிருஷி AI உதவியாளர்',
    consultingFor: 'பயிர் பதிவுக்கான ஆலோசனை',
    askAIPlaceholder: 'உரங்கள், வானிலை அல்லது பயிர் ஆரோக்கியம் குறித்து கிருஷி AI இடம் கேளுங்கள்...',
    send: 'அனுப்பு',
    govOfIndia: 'இந்திய அரசு',
    aiGreeting: 'வணக்கம்! நான் கிருஷி AI, உங்கள் மெய்நிகர் விவசாய உதவியாளர். இன்று உங்களுக்கு எப்படி உதவ முடியும்?',
    aiSimulated: 'இது ஒரு மாதிரி பதில். AI இணைக்கப்பட்டவுடன் விரிவான பதில்கள் கிடைக்கும்!',
    advIntro: 'வணக்கம்! நான் உங்கள் கிருஷி பந்து வழிகாட்டி. சிறந்த ஆலோசனையை வழங்க, உங்கள் பண்ணை பற்றி 5 கேள்விகள் கேட்க வேண்டும்.',
    advAskCrop: 'முதலில், நீங்கள் எந்தப் பயிரை வளர்க்கிறீர்கள்?',
    advAskStage: 'உங்கள் பயிரின் தற்போதைய வளர்ச்சி நிலை என்ன?',
    advAskSoil: 'உங்களிடம் என்ன வகையான மண் உள்ளது?',
    advAskPesticide: 'நீங்கள் சமீபத்தில் பூச்சிக்கொல்லியைப் பயன்படுத்தினீர்களா?',
    advAskRainfall: 'கடந்த 7 நாட்களில் சராசரி மழைப்பொழிவு (மிமீ) எவ்வளவு?',
    advFetching: 'நன்றி! உங்கள் தரவை பகுப்பாய்வு செய்து அறிக்கையைப் பெறுகிறேன்...',
    advDone: 'ஆலோசனை அமர்வு முடிந்தது.',
    advSelectOption: 'தயவுசெய்து மேலே உள்ள விருப்பத்தைத் தேர்ந்தெடுக்கவும்.',
    advError: 'இணைக்க முடியவில்லை!',
    advYes: 'ஆம்',
    advNo: 'இல்லை',
    marketPageTitle: 'நேரடி மண்டி விலைகள்',
    marketPageDesc: 'உங்கள் பயிருக்கான மிகவும் லாபகரமான மண்டியைக் கண்டறிய உங்கள் மாநிலம் முழுவதிலும் உள்ள நேரடி விவசாய சந்தை விலைகளை ஒப்பிடுக.',
    marketSelectCrop: 'விலைகளை சரிபார்க்க பயிரைத் தேர்ந்தெடுக்கவும்',
    marketChecking: 'நேரடி மண்டி விலைகள் பெறப்படுகின்றன...',
    marketCheckBtn: 'மண்டி விலைகளை சரிபார்க்கவும்',
    marketNoProfile: 'சுயவிவரம் காணப்படவில்லை',
    marketReturnDash: 'உங்கள் பயிர் மற்றும் சுயவிவர விவரங்களைச் சேர்க்க டாஷ்போர்டுக்கு திரும்பவும்.',
    marketBestPrice: 'இல் அதிக விலை கொடுக்கும் மண்டிகள்',
    marketMandiName: 'மண்டியின் பெயர்',
    marketArrivalDate: 'தேதி',
    marketModalPrice: 'விலை (₹/குவிண்டால்)',
    marketMinMax: 'குறைந்தபட்சம் - அதிகபட்சம் (₹)',
    alertDispatchedBanner: 'அபாயகரமான ஆபத்து கண்டறியப்பட்டது. உங்கள் சுயவிவரம் மற்றும் இருப்பிடத்துடன் உள்ளூர் விவசாய அதிகாரிக்கு அவசர எச்சரிக்கை அனுப்பப்பட்டுள்ளது.',
    outstandingLoanAmt: 'நிலுவை தொகை (₹)',
    annualIncome: 'மதிப்பிடப்பட்ட ஆண்டு வருமானம் (₹)',
    distressEngineTitle: 'விவசாயி இன்னல் இயந்திரம்',
    distressEngineDesc: 'விவசாய இன்னல் அபாயத்தை கணிக்க இந்த கருவி வானிலை, சந்தை விலைகள் மற்றும் நிதி வரலாற்றை பகுப்பாய்வு செய்கிறது.',
    distressResultTitle: 'இன்னல் மதிப்பீட்டு முடிவு',
    distressRisk: 'அபாயம்',
    distressKeyFactors: 'முக்கிய அபாய காரணிகள்',
    distressNoRisk: 'உடனடி அபாய காரணிகள் எதுவும் கண்டறியப்படவில்லை.',
    distressCalcAnother: 'மற்றொரு பயிரை கணக்கிடுக',
    distressSelectCrop: 'பகுப்பாய்வு செய்ய பயிரைத் தேர்ந்தெடுக்கவும்',
    distressDataSummary: 'தரவு சுருக்கம் (தானாக நிரப்பப்பட்டது)',
    distressLocation: 'இடம்',
    distressLoanAmt: 'கடன் தொகை',
    distressAnalyzing: 'நிகழ்நேர தரவு பகுப்பாய்வு செய்யப்படுகிறது...',
    distressCalcBtn: 'இன்னல் மதிப்பெண்ணை கணக்கிடுக',
    distressNoProfile: 'சுயவிவரம் காணப்படவில்லை',
    distressReturnDash: 'உங்கள் பயிர் மற்றும் சுயவிவர விவரங்களைச் சேர்க்க டாஷ்போர்டுக்கு திரும்பவும்.',
    riskLow: 'குறைவான',
    riskMedium: 'நடுத்தர',
    riskHigh: 'அதிக',
    advSoilSfx: 'மண்',
    crop_rice: 'அரிசி',
    crop_wheat: 'கோதுமை',
    crop_maize: 'மக்காச்சோளம்',
    crop_chickpea: 'கொண்டைக்கடலை',
    crop_pigeon_pea: 'துவரம் பருப்பு',
    crop_cotton: 'பருத்தி',
    crop_sugarcane: 'கரும்பு',
    crop_tomato: 'தக்காளி',
    crop_potato: 'உருளைக்கிழங்கு',
    stage_sowing: 'விதைப்பு',
    stage_vegetative: 'தாவர நிலை',
    stage_flowering: 'பூக்கும் பருவம்',
    stage_fruiting: 'காய்க்கும் பருவம்',
    stage_maturity: 'முதிர்ச்சி',
    soil_sandy: 'மணல்',
    soil_loamy: 'வண்டல்',
    soil_clay: 'களிமண்',
    logOutBtn: 'வெளியேறு',
    distressScoreTitle: 'நிதி நெருக்கடி மதிப்பெண்',
    distressScoreDesc: 'உள்ளூர் வானிலை மற்றும் சந்தை தரவுகளின் அடிப்படையில் அபாய மதிப்பீட்டைக் கணக்கிடுங்கள்',
    calculateScoreBtn: 'மதிப்பெண்ணைக் கணக்கிடுங்கள்',
    liveMandiTitle: 'நேரடி மண்டி விலைகள்',
    mandiDesc: 'மிகவும் லாபகரமான மண்டியைக் கண்டறிய உங்கள் மாநிலம் முழுவதும் உள்ள விவசாய சந்தை விலைகளை ஒப்பிடுக.',
    checkPricesBtn: 'விலைகளை சரிபார்க்கவும்',
    syncingCropStatus: '⏳ ஒத்திசைக்கப்படுகிறது...',
},
  te: {
    appTitle: 'కృషి బంధు',
    portalSubtitle: 'రైతు మరియు పంట సమాచార నమోదు పోర్టల్',
    selectLanguage: 'మీ ప్రాధాన్య భాషను ఎంచుకోండి',
    stepLanguage: '1. భాష',
    stepAccount: '2. ఖాతా వివరాలు',
    stepLocation: '3. ప్రాంతం & జిల్లా',
    stepCropLand: '4. పంట & భూమి పరిమాణం',
    stepAgriDetails: '5. నేల & నీటి పారుదల',
    stepFinancial: '6. రుణం వివరాలు',
    fullName: 'పూర్తి పేరు',
    mobileNumber: 'మొబైల్ సంఖ్య',
    password: 'పాస్‌వర్డ్',
    loginTitle: 'కృషి బంధులోకి లాగిన్ అవ్వండి',
    signupTitle: 'రైతు నమోదు',
    locationTitle: 'ప్రాంతం / జిల్లా సమాచారం',
    stateLabel: 'రాష్ట్రం',
    districtLabel: 'జిల్లా',
    manualInputToggle: 'లేదా చిరునామాను మాన్యువల్‌గా నమోదు చేయండి',
    manualAddressLabel: 'మాన్యువల్ ప్రాంతం / చిరునామా',
    fetchGpsLocation: 'జీపీఎస్ ద్వారా లొకేషన్‌ను కనుగొనండి',
    cropLabel: 'పంటను ఎంచుకోండి',
    customCropLabel: 'పంట పేరును పేర్కొనండి',
    landSizeLabel: 'భూమి పరిమాణం',
    landUnitLabel: 'యూనిట్',
    sowingDateLabel: 'విత్తనాలు నాటిన తేదీ',
    irrigationTypeLabel: 'నీటి పారుదల రకం',
    soilTypeLabel: 'నేల రకం',
    expectedHarvestDateLabel: 'కోత అంచనా తేదీ',
    loanAmountLabel: 'అంచనా రుణ మొత్తం (₹)',
    loanDueDateLabel: 'రుణం చెల్లింపు గడువు తేదీ',
    nextButton: 'తరువాతి మెట్టు',
    backButton: 'వెనుకకు',
    submitButton: 'సుపాబేస్ డేటాబేస్‌లో సమర్పించండి',
    signInButton: 'సైన్ ఇన్ చేయండి',
    dontHaveAccount: 'ఖాతా లేదా?',
    alreadyHaveAccount: 'ఇప్పటికే నమోదయ్యారా?',
    saving: 'డేటాను భద్రపరుస్తోంది...',
    successMsg: 'రైతు మరియు పంట సమాచారం విజయవంతంగా నమోదైంది!',
      dashboardTitle: 'కృషి బంధు డాష్‌బోర్డ్',
    registeredFarmerLabel: 'నమోదైన రైతు',
    loadingProfile: 'ప్రొఫైల్ లోడ్ అవుతోంది...',
    mobileLabel: 'మొబైల్',
    locationLabel: 'ప్రాంతం / జిల్లా',
    registerNewCrop: 'కొత్త పంట నమోదు చేయండి',
    recordedInfo: 'నమోదైన రైతు & పంట సమాచారం',
    recordsSaved: 'పోస్ట్‌గ్రెస్‌లో సేవ్ చేయబడిన రికార్డులు',
    syncing: 'డేటాబేస్‌తో సమకాలీకరించబడుతోంది...',
    noEntries: 'ఇంకా ఎలాంటి పంట రికార్డులు లేవు.',
    clickRegisterMsg: 'పంట వివరాలను సమర్పించడానికి క్లిక్ చేయండి.',
    addEntryHeader: 'కొత్త నమోదు',
    cancel: 'రద్దు చేయి',
    submitEntry: 'సమర్పించు',
    cropRecordNum: 'పంట రికార్డ్',
    savedToSupabase: 'సేవ్ చేయబడింది',
    soilTypeDisp: 'నేల రకం',
    irrigationDisp: 'నీటి పారుదల',
    sowingDateDisp: 'విత్తిన తేదీ',
    expectedHarvestDisp: 'అంచనా కోత',
    loanDueDateDisp: 'గడువు తేదీ',
    approxLoanAmt: 'అంచనా రుణ మొత్తం',
    consultAI: 'కృషి AI ని అడగండి',
    backToDashboard: 'డాష్‌బోర్డ్‌కు తిరిగి వెళ్ళండి',
    aiAssistant: 'కృషి AI సహాయకుడు',
    consultingFor: 'పంట రికార్డ్ కోసం సంప్రదింపులు',
    askAIPlaceholder: 'ఎరువులు, వాతావరణం గురించి అడగండి...',
    send: 'పంపండి',
    govOfIndia: 'భారత ప్రభుత్వం',
    aiGreeting: 'నమస్కారం! నేను కృషి AI ని. నేను మీకు ఎలా సహాయపడగలను?',
    aiSimulated: 'ఇది నమూనా ప్రతిస్పందన మాత్రమే.',
    advIntro: 'నమస్కారం! నేను మీ కృషి బంధు సలహాదారుని. 5 ప్రశ్నలు అడగనివ్వండి.',
    advAskCrop: 'మొదట, మీరు ఏ పంటను పండిస్తున్నారు?',
    advAskStage: 'పంట ప్రస్తుత దశ ఏమిటి?',
    advAskSoil: 'మీకు ఎలాంటి నేల ఉంది?',
    advAskPesticide: 'మీరు ఇటీవల పురుగుమందు వాడారా?',
    advAskRainfall: 'గత 7 రోజుల్లో సగటు వర్షపాతం (మిమీ) ఎంత?',
    advFetching: 'ధన్యవాదాలు! నివేదికను పొందుతున్నాను...',
    advDone: 'సలహా సెషన్ పూర్తయింది.',
    advSelectOption: 'దయచేసి ఎంపికను ఎంచుకోండి.',
    advError: 'కనెక్ట్ కాలేదు!',
    advYes: 'అవును',
    advNo: 'కాదు',
    marketPageTitle: 'లైవ్ మండి ధరలు',
    marketPageDesc: 'మీ పంటకు అత్యంత లాభదాయకమైన మండిని కనుగొనడానికి మీ రాష్ట్ర వ్యాప్తంగా ఉన్న లైవ్ వ్యవసాయ మార్కెట్ ధరలను పోల్చండి.',
    marketSelectCrop: 'ధరలను తనిఖీ చేయడానికి పంటను ఎంచుకోండి',
    marketChecking: 'లైవ్ మండి ధరలను పొందుతోంది...',
    marketCheckBtn: 'మండి ధరలను తనిఖీ చేయండి',
    marketNoProfile: 'ప్రొఫైల్ కనుగొనబడలేదు',
    marketReturnDash: 'దయచేసి మీ పంట మరియు ప్రొఫైల్ వివరాలను జోడించడానికి డాష్‌బోర్డ్‌కు తిరిగి వెళ్లండి.',
    marketBestPrice: 'లో అత్యధిక చెల్లింపు మండీలు',
    marketMandiName: 'మండి పేరు',
    marketArrivalDate: 'తేదీ',
    marketModalPrice: 'ధర (₹/క్వింటాల్)',
    marketMinMax: 'కనిష్ఠ - గరిష్ఠ (₹)',
    alertDispatchedBanner: 'క్లిష్టమైన ప్రమాదం కనుగొనబడింది. మీ ప్రొఫైల్ మరియు స్థానంతో స్థానిక వ్యవసాయ అధికారికి అత్యవసర హెచ్చరిక పంపబడింది.',
    outstandingLoanAmt: 'బకాయి మొత్తం (₹)',
    annualIncome: 'అంచనా వేసిన వార్షిక ఆదాయం (₹)',
    distressEngineTitle: 'రైతు కష్టాల ఇంజిన్',
    distressEngineDesc: 'ఈ సాధనం వాతావరణం, మార్కెట్ ధరలు మరియు ఆర్థిక చరిత్రను విశ్లేషిస్తుంది.',
    distressResultTitle: 'అంచనా ఫలితం',
    distressRisk: 'ప్రమాదం',
    distressKeyFactors: 'ముఖ్యమైన ప్రమాద కారకాలు',
    distressNoRisk: 'ప్రస్తుతానికి ఎటువంటి ప్రమాద కారకాలు లేవు.',
    distressCalcAnother: 'మరొక పంటను లెక్కించండి',
    distressSelectCrop: 'విశ్లేషించడానికి పంటను ఎంచుకోండి',
    distressDataSummary: 'డేటా సారాంశం',
    distressLocation: 'స్థానం',
    distressLoanAmt: 'రుణం మొత్తం',
    distressAnalyzing: 'డేటాను విశ్లేషిస్తోంది...',
    distressCalcBtn: 'స్కోర్‌ను లెక్కించండి',
    distressNoProfile: 'ప్రొఫైల్ కనుగొనబడలేదు',
    distressReturnDash: 'దయచేసి డాష్‌బోర్డ్‌కు తిరిగి వెళ్లండి.',
    riskLow: 'తక్కువ',
    riskMedium: 'మధ్యస్థ',
    riskHigh: 'అధిక',
    advSoilSfx: 'నేల',
    crop_rice: 'వరి',
    crop_wheat: 'గోధుమ',
    crop_maize: 'మొక్కజొన్న',
    crop_chickpea: 'శనగలు',
    crop_pigeon_pea: 'కందులు',
    crop_cotton: 'పత్తి',
    crop_sugarcane: 'చెరకు',
    crop_tomato: 'టమాటా',
    crop_potato: 'బంగాళాదుంప',
    stage_sowing: 'విత్తడం',
    stage_vegetative: 'ఏపుగా పెరిగే దశ',
    stage_flowering: 'పూత దశ',
    stage_fruiting: 'కాత దశ',
    stage_maturity: 'పక్వదశ',
    soil_sandy: 'ఇసుక',
    soil_loamy: 'మట్టి',
    soil_clay: 'బంకమట్టి',
    logOutBtn: 'లాగ్ అవుట్',
    distressScoreTitle: 'ఆర్థిక ఒత్తిడి స్కోర్',
    distressScoreDesc: 'ప్రాంతీయ వాతావరణం మరియు మార్కెట్ డేటా ఆధారంగా ప్రమాద అంచనాను లెక్కించండి',
    calculateScoreBtn: 'స్కోర్‌ను లెక్కించండి',
    liveMandiTitle: 'లైవ్ మండి ధరలు',
    mandiDesc: 'అత్యంత లాభదాయకమైన మండిని కనుగొనడానికి మీ రాష్ట్ర వ్యాప్తంగా ఉన్న వ్యవసాయ మార్కెట్ ధరలను పోల్చండి.',
    checkPricesBtn: 'ధరలను తనిఖీ చేయండి',
    syncingCropStatus: '⏳ సమకాలీకరించబడుతోంది...',
},
  mr: {
    appTitle: 'कृषी बंधू',
    portalSubtitle: 'शेतकरी व पीक माहिती नोंदणी पोर्टल',
    selectLanguage: 'आपली आवडती भाषा निवडा',
    stepLanguage: '1. भाषा',
    stepAccount: '2. खाते तपशील',
    stepLocation: '3. स्थान व जिल्हा',
    stepCropLand: '4. पीक व जमिनीचे क्षेत्र',
    stepAgriDetails: '5. माती व सिंचन',
    stepFinancial: '6. कर्जाचा तपशील',
    fullName: 'पूर्ण नाव',
    mobileNumber: 'मोबाईल नंबर',
    password: 'पासवर्ड',
    loginTitle: 'कृषी बंधू मध्ये साइन इन करा',
    signupTitle: 'शेतकरी नोंदणी',
    locationTitle: 'स्थान / जिल्हा माहिती',
    stateLabel: 'राज्य',
    districtLabel: 'जिल्हा',
    manualInputToggle: 'किंवा स्थान स्वतः टाईप करा',
    manualAddressLabel: 'स्थान / पत्ता',
    fetchGpsLocation: 'जीपीएस द्वारे स्थान मिळवा',
    cropLabel: 'पीक निवडा',
    customCropLabel: 'पिकाचे नाव लिहा',
    landSizeLabel: 'जमिनीचे क्षेत्रफळ',
    landUnitLabel: 'एकक',
    sowingDateLabel: 'पेरणीची तारीख',
    irrigationTypeLabel: 'सिंचनाचा प्रकार',
    soilTypeLabel: 'मातीचा प्रकार',
    expectedHarvestDateLabel: 'कापणीची अपेक्षित तारीख',
    loanAmountLabel: 'अंदाजित कर्ज रक्कम (₹)',
    loanDueDateLabel: 'कर्ज परतफेडीची तारीख',
    nextButton: 'पुढील पायरी',
    backButton: 'मागे',
    submitButton: 'सुपाबेस डेटाबेसमध्ये सबमिट करा',
    signInButton: 'साइन इन करा',
    dontHaveAccount: 'खाते नाही का?',
    alreadyHaveAccount: 'आधीच नोंदणी केली आहे?',
    saving: 'डेटा जतन करत आहे...',
    successMsg: 'शेतकरी आणि पीक माहिती यशस्वीरित्या नोंदवली गेली!',
      dashboardTitle: 'कृषी बंधू डॅशबोर्ड',
    registeredFarmerLabel: 'नोंदणीकृत शेतकरी',
    loadingProfile: 'प्रोफाइल लोड होत आहे...',
    mobileLabel: 'मोबाईल',
    locationLabel: 'स्थान / जिल्हा',
    registerNewCrop: 'नवीन पीक नोंदणी करा',
    recordedInfo: 'नोंदणीकृत शेतकरी आणि पीक माहिती',
    recordsSaved: 'डेटाबेसमध्ये जतन केलेल्या नोंदी',
    syncing: 'डेटाबेससह सिंक करत आहे...',
    noEntries: 'अद्याप कोणतीही पीक नोंदणी नाही.',
    clickRegisterMsg: 'माहिती सबमिट करण्यासाठी क्लिक करा.',
    addEntryHeader: 'नवीन नोंदणी',
    cancel: 'रद्द करा',
    submitEntry: 'सबमिट करा',
    cropRecordNum: 'पीक रेकॉर्ड',
    savedToSupabase: 'जतन केले',
    soilTypeDisp: 'मातीचा प्रकार',
    irrigationDisp: 'सिंचन',
    sowingDateDisp: 'पेरणीची तारीख',
    expectedHarvestDisp: 'अपेक्षित कापणी',
    loanDueDateDisp: 'कर्ज परतफेडीची तारीख',
    approxLoanAmt: 'अंदाजित कर्ज रक्कम',
    consultAI: 'कृषी AI चा सल्ला घ्या',
    backToDashboard: 'डॅशबोर्डवर परत जा',
    aiAssistant: 'कृषी AI सहाय्यक',
    consultingFor: 'पीक रेकॉर्डसाठी सल्लामसलत',
    askAIPlaceholder: 'खते किंवा हवामानाबद्दल विचारा...',
    send: 'पाठवा',
    govOfIndia: 'भारत सरकार',
    aiGreeting: 'नमस्कार! मी कृषी AI आहे. मी तुम्हाला कशी मदत करू शकतो?',
    aiSimulated: 'हा केवळ नमुना प्रतिसाद आहे.',
    advIntro: 'नमस्कार! मी तुमचा कृषी बंधू सल्लागार आहे. मी तुम्हाला 5 प्रश्न विचारू इच्छितो.',
    advAskCrop: 'प्रथम, आपण कोणते पीक घेत आहात?',
    advAskStage: 'पिकाच्या वाढीचा सध्याचा टप्पा कोणता आहे?',
    advAskSoil: 'तुमच्याकडे कोणत्या प्रकारची माती आहे?',
    advAskPesticide: 'तुम्ही अलीकडे कीटकनाशक वापरले आहे का?',
    advAskRainfall: 'गेल्या 7 दिवसात सरासरी पाऊस (मिमी) किती पडला?',
    advFetching: 'धन्यवाद! अहवाल आणत आहे...',
    advDone: 'सल्ला सत्र पूर्ण झाले.',
    advSelectOption: 'कृपया पर्याय निवडा.',
    advError: 'कनेक्ट होऊ शकले नाही!',
    advYes: 'होय',
    advNo: 'नाही',
    marketPageTitle: 'थेट बाजारभाव (मंडी)',
    marketPageDesc: 'तुमच्या पिकासाठी सर्वात फायदेशीर मंडी शोधण्यासाठी राज्यभरातील थेट कृषी बाजारभावांची तुलना करा.',
    marketSelectCrop: 'भाव तपासण्यासाठी पीक निवडा',
    marketChecking: 'थेट मंडी भाव मिळवत आहे...',
    marketCheckBtn: 'मंडी भाव तपासा',
    marketNoProfile: 'प्रोफाइल आढळले नाही',
    marketReturnDash: 'कृपया तुमचे पीक आणि प्रोफाइल तपशील जोडण्यासाठी डॅशबोर्डवर परत जा.',
    marketBestPrice: 'मध्ये सर्वाधिक भाव देणाऱ्या मंड्या',
    marketMandiName: 'मंडीचे नाव',
    marketArrivalDate: 'दिनांक',
    marketModalPrice: 'भाव (₹/क्विंटल)',
    marketMinMax: 'किमान - कमाल (₹)',
    alertDispatchedBanner: 'गंभीर धोका आढळला. तुमचे प्रोफाइल आणि स्थानासह स्थानिक कृषी अधिकाऱ्याला तातडीचा इशारा पाठवला गेला आहे.',
    outstandingLoanAmt: 'थकबाकी (₹)',
    annualIncome: 'अंदाजित वार्षिक उत्पन्न (₹)',
    distressEngineTitle: 'शेतकरी संकट इंजिन',
    distressEngineDesc: 'हे साधन हवामान, बाजारातील किमती आणि आर्थिक इतिहासाचे विश्लेषण करते.',
    distressResultTitle: 'संकट मूल्यमापन निकाल',
    distressRisk: 'धोका',
    distressKeyFactors: 'मुख्य धोक्याचे घटक',
    distressNoRisk: 'कोणतेही तात्काळ धोक्याचे घटक आढळले नाहीत.',
    distressCalcAnother: 'दुसऱ्या पिकाची गणना करा',
    distressSelectCrop: 'पिक निवडा',
    distressDataSummary: 'डेटा सारांश',
    distressLocation: 'ठिकाण',
    distressLoanAmt: 'कर्जाची रक्कम',
    distressAnalyzing: 'डेटाचे विश्लेषण करत आहे...',
    distressCalcBtn: 'स्कोअरची गणना करा',
    distressNoProfile: 'प्रोफाइल आढळले नाही',
    distressReturnDash: 'कृपया डॅशबोर्डवर परत जा.',
    riskLow: 'कमी',
    riskMedium: 'मध्यम',
    riskHigh: 'उच्च',
    advSoilSfx: 'माती',
    crop_rice: 'तांदूळ',
    crop_wheat: 'गहू',
    crop_maize: 'मका',
    crop_chickpea: 'हरभरा',
    crop_pigeon_pea: 'तूर',
    crop_cotton: 'कापूस',
    crop_sugarcane: 'ऊस',
    crop_tomato: 'टोमॅटो',
    crop_potato: 'बटाटा',
    stage_sowing: 'पेरणी',
    stage_vegetative: 'शाकीय वाढ',
    stage_flowering: 'फुलोरा',
    stage_fruiting: 'फळधारणा',
    stage_maturity: 'परिपक्वता',
    soil_sandy: 'वालुकामय',
    soil_loamy: 'चिकणमाती',
    soil_clay: 'माती',
    logOutBtn: 'लॉग आउट',
    distressScoreTitle: 'आर्थिक संकटाचा स्कोअर',
    distressScoreDesc: 'प्रादेशिक हवामान आणि बाजारातील डेटावर आधारित धोक्याचे मूल्यांकन करा',
    calculateScoreBtn: 'स्कोअरची गणना करा',
    liveMandiTitle: 'थेट बाजारभाव',
    mandiDesc: 'सर्वाधिक फायदेशीर बाजार शोधण्यासाठी राज्यभरातील कृषी बाजारभावांची तुलना करा.',
    checkPricesBtn: 'किमती तपासा',
    syncingCropStatus: '⏳ सिंक करत आहे...',
},
  bn: {
    appTitle: 'কৃষি বন্ধু',
    portalSubtitle: 'কৃষক ও ফসলের তথ্য নিবন্ধন পোর্টাল',
    selectLanguage: 'আপনার পছন্দের ভাষা নির্বাচন করুন',
    stepLanguage: '১. ভাষা',
    stepAccount: '২. অ্যাকাউন্টের বিবরণ',
    stepLocation: '৩. অবস্থান ও জেলা',
    stepCropLand: '৪. ফসল ও জমির পরিমাণ',
    stepAgriDetails: '৫. মাটি ও সেচ ব্যবস্থা',
    stepFinancial: '৬. ঋণের বিবরণ',
    fullName: 'সম্পূর্ণ নাম',
    mobileNumber: 'মোবাইল নম্বর',
    password: 'পাসওয়ার্ড',
    loginTitle: 'কৃষি বন্ধুতে সাইন ইন করুন',
    signupTitle: 'কৃষক নিবন্ধন',
    locationTitle: 'অবস্থান / জেলার তথ্য',
    stateLabel: 'রাজ্য',
    districtLabel: 'জেলা',
    manualInputToggle: 'অথবা ঠিকানা নিজে লিখুন',
    manualAddressLabel: 'হাতে লেখা ঠিকানা / অবস্থান',
    fetchGpsLocation: 'জিপিএস দিয়ে অবস্থান সনাক্ত করুন',
    cropLabel: 'ফসল নির্বাচন করুন',
    customCropLabel: 'ফসলের নাম লিখুন',
    landSizeLabel: 'জমির পরিমাণ',
    landUnitLabel: 'একক',
    sowingDateLabel: 'বপনের তারিখ',
    irrigationTypeLabel: 'সেচের ধরন',
    soilTypeLabel: 'মাটির ধরন',
    expectedHarvestDateLabel: 'ফসল কাটার আনুমানিক তারিখ',
    loanAmountLabel: 'আনুমানিক ঋণের পরিমাণ (₹)',
    loanDueDateLabel: 'ঋণ পরিশোধের তারিখ',
    nextButton: 'পরবর্তী ধাপ',
    backButton: 'পেছনে যান',
    submitButton: 'সুপাবেস ডাটাবেসে জমা দিন',
    signInButton: 'সাইন ইন করুন',
    dontHaveAccount: 'অ্যাকাউন্ট নেই?',
    alreadyHaveAccount: 'ইতিমধ্যে নিবন্ধিত?',
    saving: 'তথ্য সংরক্ষণ করা হচ্ছে...',
    successMsg: 'কৃষক এবং ফসলের তথ্য সফলভাবে নিবন্ধিত হয়েছে!',
    dashboardTitle: 'কৃষি বন্ধু ড্যাশবোর্ড',
    registeredFarmerLabel: 'নিবন্ধিত কৃষক',
    loadingProfile: 'প্রোফাইল লোড হচ্ছে...',
    mobileLabel: 'মোবাইল',
    locationLabel: 'অবস্থান / জেলা',
    registerNewCrop: 'নতুন ফসল নিবন্ধন করুন',
    recordedInfo: 'নিবন্ধিত কৃষক ও ফসলের তথ্য',
    recordsSaved: 'ডাটাবেসে সংরক্ষিত রেকর্ড',
    syncing: 'ডাটাবেসের সাথে সিঙ্ক করা হচ্ছে...',
    noEntries: 'এখনও কোনো ফসলের রেকর্ড নেই।',
    clickRegisterMsg: 'তথ্য জমা দিতে ক্লিক করুন।',
    addEntryHeader: 'নতুন নিবন্ধন',
    cancel: 'বাতিল করুন',
    submitEntry: 'জমা দিন',
    cropRecordNum: 'ফসলের রেকর্ড',
    savedToSupabase: 'সংরক্ষিত',
    soilTypeDisp: 'মাটির ধরন',
    irrigationDisp: 'সেচ',
    sowingDateDisp: 'বপনের তারিখ',
    expectedHarvestDisp: 'প্রত্যাশিত ফসল কাটা',
    loanDueDateDisp: 'ঋণ পরিশোধের তারিখ',
    approxLoanAmt: 'আনুমানিক ঋণের পরিমাণ',
    consultAI: 'কৃষি এআই-এর সাথে পরামর্শ করুন',
    backToDashboard: 'ড্যাশবোর্ডে ফিরে যান',
    aiAssistant: 'কৃষি এআই সহকারী',
    consultingFor: 'ফসলের রেকর্ডের জন্য পরামর্শ',
    askAIPlaceholder: 'সার বা আবহাওয়া সম্পর্কে জিজ্ঞাসা করুন...',
    send: 'পাঠান',
    govOfIndia: 'ভারত সরকার',
    aiGreeting: 'নমস্কার! আমি কৃষি এআই। আমি আপনাকে কীভাবে সাহায্য করতে পারি?',
    aiSimulated: 'এটি একটি সিমুলেটেড প্রতিক্রিয়া।',
    advIntro: 'নমস্কার! আমি আপনার কৃষি বন্ধু উপদেষ্টা। আমি ৫টি প্রশ্ন জিজ্ঞাসা করব।',
    advAskCrop: 'প্রথমে, আপনি কোন ফসল চাষ করছেন?',
    advAskStage: 'আপনার ফসলের বর্তমান বৃদ্ধির পর্যায় কী?',
    advAskSoil: 'আপনার কি ধরনের মাটি আছে?',
    advAskPesticide: 'আপনি কি সম্প্রতি কীটনাশক প্রয়োগ করেছেন?',
    advAskRainfall: 'গত ৭ দিনে গড় বৃষ্টিপাত (মিমি) কত ছিল?',
    advFetching: 'ধন্যবাদ! প্রতিবেদন আনা হচ্ছে...',
    advDone: 'পরামর্শ সেশন সম্পন্ন হয়েছে।',
    advSelectOption: 'অনুগ্রহ করে একটি বিকল্প নির্বাচন করুন।',
    advError: 'সংযোগ করা যায়নি!',
    advYes: 'হ্যাঁ',
    advNo: 'না',
    marketPageTitle: 'লাইভ মান্ডি দর',
    marketPageDesc: 'আপনার ফসলের জন্য সবচেয়ে লাভজনক মান্ডি খুঁজে পেতে আপনার রাজ্য জুড়ে লাইভ কৃষি বাজারের দামের তুলনা করুন।',
    marketSelectCrop: 'দাম চেক করতে ফসল নির্বাচন করুন',
    marketChecking: 'লাইভ মান্ডি দর আনা হচ্ছে...',
    marketCheckBtn: 'মান্ডি দর চেক করুন',
    marketNoProfile: 'প্রোফাইল পাওয়া যায়নি',
    marketReturnDash: 'দয়া করে আপনার ফসল এবং প্রোফাইল বিবরণ যোগ করতে ড্যাশবোর্ডে ফিরে যান।',
    marketBestPrice: 'তে সর্বোচ্চ অর্থ প্রদানকারী মান্ডি',
    marketMandiName: 'মান্ডির নাম',
    marketArrivalDate: 'তারিখ',
    marketModalPrice: 'দাম (₹/কুইন্টাল)',
    marketMinMax: 'সর্বনিম্ন - সর্বোচ্চ (₹)',
    alertDispatchedBanner: 'গুরুতর ঝুঁকি সনাক্ত করা হয়েছে। আপনার প্রোফাইল এবং অবস্থানের সাথে স্থানীয় কৃষি কর্মকর্তার কাছে একটি জরুরি সতর্কতা পাঠানো হয়েছে।',
    outstandingLoanAmt: 'বকেয়া পরিমাণ (₹)',
    annualIncome: 'আনুমানিক বার্ষিক আয় (₹)',
    distressEngineTitle: 'কৃষক সংকট ইঞ্জিন',
    distressEngineDesc: 'এই টুল আবহাওয়া, বাজারের দাম এবং আর্থিক ইতিহাস বিশ্লেষণ করে।',
    distressResultTitle: 'সংকট মূল্যায়ন ফলাফল',
    distressRisk: 'ঝুঁকি',
    distressKeyFactors: 'প্রধান ঝুঁকির কারণ',
    distressNoRisk: 'কোনো তাৎক্ষণিক ঝুঁকির কারণ নেই।',
    distressCalcAnother: 'অন্য ফসলের গণনা করুন',
    distressSelectCrop: 'ফসল নির্বাচন করুন',
    distressDataSummary: 'ডেটা সারাংশ',
    distressLocation: 'অবস্থান',
    distressLoanAmt: 'ঋণের পরিমাণ',
    distressAnalyzing: 'ডেটা বিশ্লেষণ করা হচ্ছে...',
    distressCalcBtn: 'স্কোর গণনা করুন',
    distressNoProfile: 'প্রোফাইল পাওয়া যায়নি',
    distressReturnDash: 'দয়া করে ড্যাশবোর্ডে ফিরে যান।',
    riskLow: 'কম',
    riskMedium: 'মাঝারি',
    riskHigh: 'উচ্চ',
    advSoilSfx: 'মাটি',
    crop_rice: 'ধান',
    crop_wheat: 'গম',
    crop_maize: 'ভুট্টা',
    crop_chickpea: 'ছোলা',
    crop_pigeon_pea: 'অড়হর',
    crop_cotton: 'তুলা',
    crop_sugarcane: 'আখ',
    crop_tomato: 'টমেটো',
    crop_potato: 'আলু',
    stage_sowing: 'বপন',
    stage_vegetative: 'উদ্ভিজ্জ',
    stage_flowering: 'ফুল ফোটা',
    stage_fruiting: 'ফল ধরা',
    stage_maturity: 'পরিপক্কতা',
    soil_sandy: 'বেলে',
    soil_loamy: 'দোআঁশ',
    soil_clay: 'কাদা',
  }
};

export function getTranslation(langCode: string, key: string): string {
  const dict = UI_TRANSLATIONS[langCode] || UI_TRANSLATIONS['en'];
  return dict[key] || UI_TRANSLATIONS['en'][key] || key;
}
